AllCops:
  NewCops: disable
  Exclude:
    - bin/bundle
    - node_modules/node-sass/src/libsass/extconf.rb
    - node_modules/node-sass/src/libsass/contrib/libsass.spec
    - db/schema.rb
    - db/seeds.rb
    - config/**/*
    - test/**/*
    - app/channels/**/*
    - app/helpers/*
    - app/jobs/*
    - app/mailers/*
    - Rakefile

Metrics/BlockLength:
  Exclude:
    - spec/features/*
