AllCops:
  NewCops: disable
  Exclude:
    - bin/bundle
    - node_modules/node-sass/src/libsass/extconf.rb
    - node_modules/node-sass/src/libsass/contrib/libsass.spec
    - db/schema.rb
    - db/seeds.rb
    - config/**/*
    - test/**/*
    - app/channels/**/*
    - app/helpers/*
    - app/jobs/*
    - app/mailers/*
    - Rakefile
    - bin/rails
    - config.ru

Metrics/BlockLength:
  Exclude:
    - spec/features/*
    - db/migrate/*
    
Layout/EndOfLine:
  Enabled: False
  
Metrics/MethodLength:
  Exclude:
    - db/migrate/*