development:
  adapter: postgresql
  encoding: unicode
  database: tamuicehockey_development
  pool: 5
  username: tamuicehockey
  password: hockey1

test:
  adapter: postgresql
  encoding: unicode
  database: tamuicehockey_test
  pool: 5
  username: tamuicehockey
  password: hockey1