# frozen_string_literal: true

# helper for games module
module GamesHelper
  def game_identity(game)
    "vs #{game.against_team} on #{game.date.strftime('%Y-%m-%d')}"
  end

  def us_states
    [
      ['Please Choose a State...'],
      %w[Alabama AL],
      %w[Alaska AK],
      %w[Alberta AB],
      %w[Arizona AZ],
      %w[Arkansas AR],
      ['British Columbia', 'BC'],
      %w[California CA],
      %w[Colorado CO],
      %w[Connecticut CT],
      %w[Delaware DE],
      ['District of Columbia', 'DC'],
      %w[Florida FL],
      %w[Georgia GA],
      %w[Hawaii HI],
      %w[Idaho ID],
      %w[Illinois IL],
      %w[Indiana IN],
      %w[Iowa IA],
      %w[Kansas KS],
      %w[Kentucky KY],
      %w[Louisiana LA],
      %w[Maine ME],
      %w[Manitoba MB],
      %w[Maryland MD],
      %w[Massachusetts MA],
      %w[Michigan MI],
      %w[Minnesota MN],
      %w[Mississippi MS],
      %w[Missouri MO],
      %w[Montana MT],
      %w[Nebraska NE],
      %w[Nevada NV],
      ['New Brunswick', 'NB'],
      ['New Hampshire', 'NH'],
      ['New Jersey', 'NJ'],
      ['New Mexico', 'NM'],
      ['New York', 'NY'],
      ['North Carolina', 'NC'],
      ['North Dakota', 'ND'],
      ['Nova Scotia', 'NS'],
      %w[Ohio OH],
      %w[Oklahoma OK],
      %w[Ontario ON],
      %w[Oregon OR],
      %w[Pennsylvania PA],
      ['Prince Edward Island', 'PE'],
      ['Puerto Rico', 'PR'],
      %w[Quebec QC],
      ['Rhode Island', 'RI'],
      %w[Saskatchewan SK],
      ['South Carolina', 'SC'],
      ['South Dakota', 'SD'],
      %w[Tennessee TN],
      %w[Texas TX],
      %w[Utah UT],
      %w[Vermont VT],
      %w[Virginia VA],
      %w[Washington WA],
      ['West Virginia', 'WV'],
      %w[Wisconsin WI],
      %w[Wyoming WY],
      ['International', 'Int.']
    ]
  end
end
