#main.yml

env:
  RUBY_VERSION: 2.7.x
  POSTGRES_USER: tamuicehockey
  POSTGRES_PASSWORD: hockey1
  POSTGRES_DB: tamuicehockey_development

name: Rails tests
on: [push,pull_request]

jobs:
  rubocop-test:
    name: Rubocop
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ env.RUBY_VERSION }}
      - name: Install Rubocop
        run: gem install rubocop
      - name: Check code
        run: rubocop
